import type { Analysis, RiskItem, Severity } from "./analysis-schema";
import { computeCost, formatUsd, type Usage } from "./pricing";

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low"];

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
};

function groupBySeverity(risks: RiskItem[]): Record<Severity, RiskItem[]> {
  const out: Record<Severity, RiskItem[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  };
  for (const r of risks) out[r.severity].push(r);
  return out;
}

export function buildMarkdownReport(
  analysis: Analysis,
  meta: {
    filename: string;
    model: string;
    generatedAt: Date;
    usage: Usage;
  },
): string {
  const grouped = groupBySeverity(analysis.risks);
  const cost = computeCost(meta.usage, meta.model);
  const lines: string[] = [];

  lines.push(`# Risk Analysis — ${meta.filename}`);
  lines.push("");
  lines.push(`- **Model:** ${meta.model}`);
  lines.push(`- **Generated:** ${meta.generatedAt.toISOString()}`);
  lines.push(`- **Overall score:** ${analysis.overall_score} / 100`);
  lines.push(`- **Risk level:** ${analysis.risk_level.toUpperCase()}`);
  if (cost) {
    lines.push(`- **Scan cost:** ${formatUsd(cost.total)} (${cost.tokens.input.toLocaleString()} input + ${cost.tokens.output.toLocaleString()} output tokens)`);
  } else {
    lines.push(`- **Tokens used:** ${(meta.usage.input_tokens + meta.usage.output_tokens).toLocaleString()}`);
  }
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(analysis.summary);
  lines.push("");

  for (const sev of SEVERITY_ORDER) {
    const items = grouped[sev];
    if (items.length === 0) continue;
    lines.push(`## ${SEVERITY_LABEL[sev]} (${items.length})`);
    lines.push("");
    items.forEach((r, i) => {
      lines.push(`### ${i + 1}. ${r.title}`);
      lines.push("");
      lines.push(`- **Section:** ${r.section_reference}`);
      lines.push("");
      lines.push(r.description);
      lines.push("");
      lines.push("> " + r.quote.replace(/\n/g, "\n> "));
      lines.push("");
      lines.push(`**Negotiation point:** ${r.negotiation_point}`);
      lines.push("");
    });
  }

  lines.push("---");
  lines.push(
    "Generated by Before You Sign. This is not legal advice — consult a lawyer for important agreements.",
  );

  return lines.join("\n");
}
