import { jsPDF } from "jspdf";
import type { Analysis, RiskItem, Severity } from "./analysis-schema";
import { computeCost, formatUsd, type Usage } from "./pricing";

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low"];

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
};

const SEVERITY_COLOR: Record<Severity, [number, number, number]> = {
  critical: [185, 28, 28],
  high: [194, 65, 12],
  medium: [161, 98, 7],
  low: [21, 128, 61],
};

type Cursor = { y: number };

const MARGIN = 48;
const PAGE_WIDTH = 612; // Letter @ 72dpi default for jsPDF
const PAGE_HEIGHT = 792;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function ensureSpace(doc: jsPDF, cursor: Cursor, needed: number) {
  if (cursor.y + needed > PAGE_HEIGHT - MARGIN) {
    doc.addPage();
    cursor.y = MARGIN;
  }
}

function drawText(
  doc: jsPDF,
  cursor: Cursor,
  text: string,
  opts: { size?: number; bold?: boolean; color?: [number, number, number] } = {},
) {
  const size = opts.size ?? 11;
  doc.setFont("helvetica", opts.bold ? "bold" : "normal");
  doc.setFontSize(size);
  if (opts.color) doc.setTextColor(opts.color[0], opts.color[1], opts.color[2]);
  else doc.setTextColor(20, 20, 20);

  const lines = doc.splitTextToSize(text, CONTENT_WIDTH) as string[];
  const lineHeight = size * 1.35;
  for (const line of lines) {
    ensureSpace(doc, cursor, lineHeight);
    doc.text(line, MARGIN, cursor.y);
    cursor.y += lineHeight;
  }
}

function drawQuote(doc: jsPDF, cursor: Cursor, text: string) {
  const size = 10;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(size);
  doc.setTextColor(60, 60, 60);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH - 12) as string[];
  const lineHeight = size * 1.4;
  for (const line of lines) {
    ensureSpace(doc, cursor, lineHeight);
    doc.setDrawColor(180, 180, 180);
    doc.line(MARGIN, cursor.y - lineHeight + 3, MARGIN, cursor.y + 2);
    doc.text(line, MARGIN + 10, cursor.y);
    cursor.y += lineHeight;
  }
}

function groupBySeverity(risks: RiskItem[]): Record<Severity, RiskItem[]> {
  const out: Record<Severity, RiskItem[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  };
  for (const r of risks) out[r.severity].push(r);
  return out;
}

export function buildPdfReport(
  analysis: Analysis,
  meta: {
    filename: string;
    model: string;
    generatedAt: Date;
    usage: Usage;
  },
): Blob {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const cursor: Cursor = { y: MARGIN };
  const cost = computeCost(meta.usage, meta.model);

  drawText(doc, cursor, "Risk Analysis", { size: 22, bold: true });
  drawText(doc, cursor, meta.filename, { size: 12 });
  cursor.y += 6;

  drawText(doc, cursor, `Model: ${meta.model}`, { size: 10 });
  drawText(doc, cursor, `Generated: ${meta.generatedAt.toLocaleString()}`, {
    size: 10,
  });
  if (cost) {
    drawText(
      doc,
      cursor,
      `Scan cost: ${formatUsd(cost.total)}  ·  ${cost.tokens.input.toLocaleString()} input + ${cost.tokens.output.toLocaleString()} output tokens`,
      { size: 10 },
    );
  }
  cursor.y += 12;

  drawText(
    doc,
    cursor,
    `Overall score: ${analysis.overall_score} / 100  (${analysis.risk_level.toUpperCase()})`,
    {
      size: 14,
      bold: true,
      color: SEVERITY_COLOR[analysis.risk_level],
    },
  );
  cursor.y += 8;

  drawText(doc, cursor, "Summary", { size: 14, bold: true });
  drawText(doc, cursor, analysis.summary, { size: 11 });
  cursor.y += 8;

  const grouped = groupBySeverity(analysis.risks);
  for (const sev of SEVERITY_ORDER) {
    const items = grouped[sev];
    if (items.length === 0) continue;
    cursor.y += 6;
    drawText(doc, cursor, `${SEVERITY_LABEL[sev]} (${items.length})`, {
      size: 14,
      bold: true,
      color: SEVERITY_COLOR[sev],
    });
    items.forEach((r, i) => {
      cursor.y += 4;
      drawText(doc, cursor, `${i + 1}. ${r.title}`, { size: 12, bold: true });
      drawText(doc, cursor, `Section: ${r.section_reference}`, {
        size: 10,
      });
      drawText(doc, cursor, r.description, { size: 11 });
      cursor.y += 2;
      drawQuote(doc, cursor, r.quote);
      cursor.y += 2;
      drawText(doc, cursor, `Negotiation point: ${r.negotiation_point}`, {
        size: 11,
        bold: true,
      });
    });
  }

  cursor.y += 12;
  drawText(
    doc,
    cursor,
    "Generated by Before You Sign. This is not legal advice — consult a lawyer for important agreements.",
    { size: 9, color: [120, 120, 120] },
  );

  return doc.output("blob");
}
